import type { Metadata, Viewport } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "wealthtrajectory",
  description:
    "Private, privacy-first net-worth and financial-independence planning. Track holdings, project trajectories, and stress-test against historical sequences — all client-side.",
  // Icons are auto-generated by app/icon.tsx (512x512 PNG) and
  // app/apple-icon.tsx (180x180 PNG). Next.js emits the corresponding
  // <link rel="icon"> and <link rel="apple-touch-icon"> tags. We keep
  // the SVG files in /public as scalable fallbacks referenced by the
  // PWA manifest, but the auto-generated PNGs are the primary path
  // for iOS Safari "Add to Home Screen" and Android install.
  appleWebApp: {
    capable: true,
    title: "wealthtrajectory",
    statusBarStyle: "black-translucent",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#0a0d12",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
